Update config.yml
Example MYSQL Project

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,8 +1,36 @@
-version: 2.1
-orbs:
-    hello: circleci/hello-build@0.0.5
-    
+version: 2 
+jobs:
+  build:
+    docker:
+      - image: circleci/php:7.1-apache-node-browsers
+      - image: circleci/mysql:8.0.4
+        environment:
+          MYSQL_ROOT_PASSWORD: rootpw
+          MYSQL_DATABASE: test_db
+          MYSQL_USER: user
+          MYSQL_PASSWORD: passw0rd
+     
+    steps:
+      - checkout
+      - run: 
+          name: Waiting for MYSQL to be ready 
+          command: |
+            for i in 'seq 1 10'
+            do
+              nc -z 127.0.0.1 3306 && echo "Success" && exit 0 
+              echo -n 
+              sleep 1
+            done
+            echo "Failed waiting for MYSQL" && exit 1 
+      - run: 
+          name: Install MYSQL CLI; Import dummy data; run an example query
+          command: | 
+            sudo apt-get install default-mysql-client
+            mysql -h 127.0.0.1 -u user -p passw0rd test_db < sql-data/dummy.sql
+            mysql -h 127.0.0.1 -u user -p passw0rd  --execute="Select * from test_db.Persons"
 workflows:
-    "Hello Workflow":
-        jobs:
-          - hello/hello-build
+  version: 2 
+  build-deploy:
+    jobs: 
+      - build:
+            
